name: Build and Deploy to App Center

on:
  push:
    branches:
      - Android2
  workflow_dispatch:

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
        working-directory: ./readme-android
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: readme/app/build/outputs/apk/appCenter/debug/
      - name: upload artefact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName:
          token: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DFCA0C9562BF4BD188504B74CF5A7C9D }}
          group: Collaborators
          file: readme/app/build/outputs/apk/appCenter/debug/app-appCenter-debug.apk
          notifyTesters: true
          debug: false
