name: Build and Deploy to App Center

on:
  push:
    branches:
      - Android2
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build debug APK
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: readme/app/build/outputs/apk/appCenter/debug/
      - name: upload artefact to App Center
        uses: actions/AppCenter-Github-Action@v1
        with:
          appName:
          token: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DFCA0C9562BF4BD188504B74CF5A7C9D }}
          group: Collaborators
          file: readme/app/build/outputs/apk/appCenter/debug/app-appCenter-debug.apk
          notifyTesters: true
          debug: false
