name: Build and Upload APK

on:
  push:
    branches:
      - Android

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload APK to App Center
        uses: microsoft/appcenter-action@v2
        with:
          app_name: Readme
          app_secret: ${{ secrets.APP_CENTER_APP_SECRET }}
          file: app/build/outputs/apk/appCenter/debug/app-appCenter-debug.apk
          group: Collaborators
          package: '*.apk'